#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page that contains
# The page must return an HTTP 404 error code

apt updte -y update
apt install -y nginx

echo "Hello World" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=PCE3ScHepkc;
    }
    error_page 404 /404.html;
}" > /etc/nginx/sites-enabled/default

service nginx restart
